services:
  - type: web
    name: lavalink-music-bot
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: PREFIX
        value: "!"
      - key: OWNER_ID
        sync: false
      - key: LAVALINK_HOST
        value: "lavalink.jirayu.net"
      - key: LAVALINK_PORT
        value: "13592"
      - key: LAVALINK_PASSWORD
        value: "youshallnotpass"
      - key: LAVALINK_SECURE
        value: "false"
      - key: EMOJI_PROGRESS_DOT
        value: "â€¢"
